geoportal_query_params = {"where" = "1=1", "outSR" = 4326, "outFields" = "*", "f" = "geoJSON", "resultOffset" = 0, "returnExceededLimitFeatures" = true}
timetable_url_prefix = "https://data.bus-data.dft.gov.uk/timetable/download/gtfs-file"

[[boundaries]]
"lsoa" = {"filename" = "data/resources/LSOA_boundaries.geojson", "url" = "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Lower_layer_Super_Output_Areas_2021_EW_BSC_v2/FeatureServer/0/query"}
"bua" = {"filename" = "data/resources/BUA_boundaries.geojson", "url" = "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/BUA_2022_GB/FeatureServer/0/query"}
# oa
# ttwa
# region
