name: CodeCov
on:
  push:  # all pushes
  pull_request:
    branches: ["main", "dev"]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.7
        cache: 'pip' # caching pip dependencies

    - name: Generate Report
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install coverage[toml]
        coverage run -m pytest
        coverage report xml

    - name: Upload Coverage to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/macos/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
